# Generated by Django 4.2.7 on 2023-11-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=140),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
